name: deploy ubuntu
on:
  push:
    branches:
      - main

jobs:
  SSH:
    name: SSH test
    runs-on: ubuntu-20.04
    steps:
      - name: Run scripts in server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SER2_IP }}
          username: ${{ secrets.SER2_ID }}
          password: ${{ secrets.SER2_PWD }}
          port: 22
          timeout: 40s
          script: |
            whoami
            echo "test"
