name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-20.04

    steps:
#      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: magaeTube/github_action_with_python@main
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd github_action_with_python
            git pull
